In [5]:
import numpy as np

In [49]:
def LU(A, n):
    L = np.zeros((n, n))#l INITIATED
    U = np.zeros((n, n))#u INITIATED
    for k in range(n):
        L[k, k] = 1 #aLL DIAGONALS 1
        t = 0
        for p in range(k):
            t += L[k, p] * U[p, k]
        U[k, k] = A[k, k] - t#DIAGONAL OF U BASED ON PREVIOUS VALUES
        for i in range(k + 1, n):
            t = 0
            for p in range(k):
                t += L[i, p] * U[p, k]
            L[i, k] = (A[i, k] - t) / U[k, k]#OTHER VALUES OF L
        for j in range(k+1, n):
            t = 0
            for p in range(k):
                t += L[k, p] * U[p, j]
            U[k, j] = A[k, j] - t#OTHER VALUES OF U
    return L, U
A = np.array([[1,1,1], [4,3,-1],[3,5,3]])
n = A.shape[0]
L, U = LU(A, n)
print("L:")
print(L)#printing beauty
print("U:")
print(U)#printing beauty

L:
[[ 1.  0.  0.]
 [ 4.  1.  0.]
 [ 3. -2.  1.]]
U:
[[  1.   1.   1.]
 [  0.  -1.  -5.]
 [  0.   0. -10.]]


In [50]:
np.dot(L,U)#Verification

array([[ 1.,  1.,  1.],
       [ 4.,  3., -1.],
       [ 3.,  5.,  3.]])

In [54]:
b=np.array([1,6,4])

In [51]:
def forward_substitution(L, b):#Solves the Lower triangular matrix system Lx = b using backward substitution
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        tmp = 0.0
        for j in range(i):
            tmp += L[i, j] * x[j]
        x[i] = (b[i] - tmp) / L[i, i]
    return x

In [52]:
def backward_substitution(U, b):#Solves the upper triangular system Ux = b using backward substitution
    n = len(b)
    x = np.zeros(n)
    # Start from the last equation and move upwards
    for i in range(n-1, -1, -1):#START FROM BACK
        x[i] = (b[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]#i AM TAKING DOT OF ALL PREVIOUS VALUES REMOVING IT AND THEN DIVIDING
    return x

In [56]:
Z=forward_substitution(L, b)#assuming ux=z
Z#LZ=b

array([1., 2., 5.])

In [57]:
X=backward_substitution(U, Z)#UX=Z

In [58]:
X#fINAL ANSWER

array([ 1. ,  0.5, -0.5])

In [59]:
print(X)

[ 1.   0.5 -0.5]


In [ ]:
#Algorithm is Doolittle's algorithm